# Generated by Django 3.0.4 on 2020-06-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('activiti', models.TextField()),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('mail_address', models.CharField(max_length=100)),
                ('select_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='List_of_candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.IntegerField(default=0)),
                ('_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.Candidate')),
            ],
        ),
    ]
