# Generated by Django 3.0.4 on 2020-06-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_of_candidates',
            old_name='_candidate',
            new_name='candidate_in_list',
        ),
    ]
